/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/S2eAilHRA4c
 */
import Link from "next/link";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { CardHeader, CardContent, Card } from "@/components/ui/card";
import Image from "next/image";

export function Component() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <header className="px-4 lg:px-6 h-14 flex items-center">
        <Link className="flex items-center justify-center" href="#">
          <LaptopIcon className="h-6 w-6" />
          <span className="sr-only">Acme Inc</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link
            className="text-sm font-medium hover:underline underline-offset-4"
            href="#"
          >
            Courses
          </Link>
          <Link
            className="text-sm font-medium hover:underline underline-offset-4"
            href="#"
          >
            Schedule
          </Link>
          <Link
            className="text-sm font-medium hover:underline underline-offset-4"
            href="#"
          >
            Resources
          </Link>
          <Link
            className="text-sm font-medium hover:underline underline-offset-4"
            href="#"
          >
            Profile
          </Link>
        </nav>
      </header>
      <main className="flex-1">
        <section className="w-full bg-hero bg-center bg-cover">
          <div className="relative py-12 md:py-24 lg:py-32 top-0 left-0 w-full h-full z-10 bg-black/20 flex items-center justify-center flex-col">
            <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6 lg:gap-10">
              <div className="space-y-3">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-6xl">
                  Welcome to Acme University
                </h2>
                <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  Learn from anywhere. World-class education at your fingertips.
                </p>
              </div>
              <div className="mx-auto w-full max-w-sm space-y-2">
                <Button type="submit" size="lg" className="text-lg">
                  Sign In
                </Button>
                <p className="text-xs text-gray-500 dark:text-gray-400">
                  Sign in to access your account.
                  <Link className="underline underline-offset-2" href="#">
                    Forgot Password?
                  </Link>
                </p>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 border-t">
          <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6">
            <div className="space-y-3">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
                Featured Courses
              </h2>
              <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Our expertly curated selection of courses to kickstart your
                learning journey.
              </p>
            </div>
            <div className="mx-auto grid max-w-5xl items-start gap-6 lg:grid-cols-2 lg:gap-12">
              <div className="grid gap-2">
                <h3 className="text-xl font-bold">
                  Introduction to Computer Science
                </h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Learn the basics of programming with Python in this
                  comprehensive course.
                </p>
              </div>
              <div className="grid gap-2">
                <h3 className="text-xl font-bold">Mastering Data Analytics</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Dive into the world of data with SQL, Excel, and Tableau to
                  analyze and visualize data.
                </p>
              </div>
              <div className="grid gap-2">
                <h3 className="text-xl font-bold">Web Development Bootcamp</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Build modern websites with HTML, CSS, and JavaScript in this
                  hands-on course.
                </p>
              </div>
              <div className="grid gap-2">
                <h3 className="text-xl font-bold">
                  Artificial Intelligence Fundamentals
                </h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Explore the principles of AI and machine learning with
                  real-world examples.
                </p>
              </div>
            </div>
            <div className="flex justify-center">
              <Link
                className="inline-flex h-10 items-center justify-center rounded-md border border-gray-200 bg-white px-8 text-sm font-medium shadow-sm transition-colors hover:bg-gray-100 hover:text-gray-900 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus-visible:ring-gray-300"
                href="#"
              >
                View All Courses
              </Link>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800">
          <div className="container grid items-center gap-4 px-4 md:px-6">
            <div className="space-y-2">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">
                Upcoming Live Sessions
              </h2>
              <p className="text-gray-500 dark:text-gray-400">
                Join our live classes with industry experts.
              </p>
            </div>
            <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
              <Card>
                <CardHeader className="pb-0">
                  <Image
                    alt="Cover image"
                    className="aspect-video rounded-t-lg object-cover"
                    height="150"
                    src="/placeholder.svg"
                    width="300"
                  />
                  <div className="space-y-2 px-4">
                    <h3 className="text-base font-bold">
                      Introduction to Psychology
                    </h3>
                    <p className="text-sm text-gray-500 dark:text-gray-400">
                      Live Session with Prof. Smith
                    </p>
                  </div>
                </CardHeader>
                <CardContent className="pt-4">
                  <div className="flex items-center space-x-2">
                    <UserIcon className="h-4 w-4" />
                    <span className="text-sm">25 Students</span>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardHeader className="pb-0">
                  <Image
                    alt="Cover image"
                    className="aspect-video rounded-t-lg object-cover"
                    height="150"
                    src="/placeholder.svg"
                    width="300"
                  />
                  <div className="space-y-2 px-4">
                    <h3 className="text-base font-bold">
                      Introduction to Psychology
                    </h3>
                    <p className="text-sm text-gray-500 dark:text-gray-400">
                      Live Session with Prof. Smith
                    </p>
                  </div>
                </CardHeader>
                <CardContent className="pt-4">
                  <div className="flex items-center space-x-2">
                    <UserIcon className="h-4 w-4" />
                    <span className="text-sm">25 Students</span>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardHeader className="pb-0">
                  <Image
                    alt="Cover image"
                    className="aspect-video rounded-t-lg object-cover"
                    height="150"
                    src="/placeholder.svg"
                    width="300"
                  />
                  <div className="space-y-2 px-4">
                    <h3 className="text-base font-bold">
                      Introduction to Psychology
                    </h3>
                    <p className="text-sm text-gray-500 dark:text-gray-400">
                      Live Session with Prof. Smith
                    </p>
                  </div>
                </CardHeader>
                <CardContent className="pt-4">
                  <div className="flex items-center space-x-2">
                    <UserIcon className="h-4 w-4" />
                    <span className="text-sm">25 Students</span>
                  </div>
                </CardContent>
              </Card>
            </div>
            <div className="flex justify-center">
              <Link
                className="inline-flex h-10 items-center justify-center rounded-md border border-gray-200 bg-white px-8 text-sm font-medium shadow-sm transition-colors hover:bg-gray-100 hover:text-gray-900 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus-visible:ring-gray-300"
                href="#"
              >
                View All Sessions
              </Link>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container grid items-center gap-4 px-4 md:px-6">
            <div className="space-y-2">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">
                Student Testimonials
              </h2>
              <p className="text-gray-500 dark:text-gray-400">
                Don&apos;t take our word for it. Here&apos;s what our students
                have to say.
              </p>
            </div>
            <div className="mx-auto grid max-w-5xl items-start gap-8 sm:grid-cols-2 md:gap-12 lg:gap-16">
              <div className="grid gap-2">
                <h3 className="text-xl font-bold">Life-changing Experience</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  &quot;The courses at Acme University have been a life-changing
                  experience. The professors are knowledgeable and the platform
                  is easy to use.&quot;
                </p>
                <div className="flex items-center space-x-2">
                  <Image
                    alt="Avatar"
                    className="rounded-full"
                    height="40"
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "40/40",
                      objectFit: "cover",
                    }}
                    width="40"
                  />
                  <span className="text-sm font-semibold">Alice Johnson</span>
                </div>
              </div>
              <div className="grid gap-2">
                <h3 className="text-xl font-bold">Inspiring Instructors</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  &quot;The instructors are inspiring and the content is
                  engaging. I feel motivated to learn and the support from the
                  community is amazing.&quot;
                </p>
                <div className="flex items-center space-x-2">
                  <Image
                    alt="Avatar"
                    className="rounded-full"
                    height="40"
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "40/40",
                      objectFit: "cover",
                    }}
                    width="40"
                  />
                  <span className="text-sm font-semibold">Bob Smith</span>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <p className="text-xs text-gray-500 dark:text-gray-400">
          © 2024 Acme Inc. All rights reserved.
        </p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Terms of Service
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Privacy
          </Link>
        </nav>
      </footer>
    </div>
  );
}

function LaptopIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 16V7a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v9m16 0H4m16 0 1.28 2.55a1 1 0 0 1-.9 1.45H3.62a1 1 0 0 1-.9-1.45L4 16" />
    </svg>
  );
}

function UserIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  );
}
