/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/O7pD8pJwnxi
 */
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card"
import { TableCell, TableRow, TableBody, Table } from "@/components/ui/table"
import { PopoverTrigger, PopoverContent, Popover } from "@/components/ui/popover"

export function LoggedInV1() {
  return (
    <div className="flex flex-col w-full min-h-screen">
      <header className="flex items-center h-16 px-4 border-b shrink-0 md:px-6">
        <nav className="flex-col hidden gap-6 text-lg font-medium md:flex md:flex-row md:items-center md:gap-5 md:text-sm lg:gap-6">
          <Link className="flex items-center gap-2 text-lg font-semibold md:text-base" href="#">
            <Package2Icon className="w-6 h-6" />
            <span className="sr-only">Acme Inc</span>
          </Link>
          <Link className="text-gray-500 dark:text-gray-400" href="#">
            Courses
          </Link>
          <Link className="text-gray-500 dark:text-gray-400" href="#">
            Assignments
          </Link>
          <Link className="text-gray-500 dark:text-gray-400" href="#">
            Grades
          </Link>
          <Link className="text-gray-500 dark:text-gray-400" href="#">
            Resources
          </Link>
        </nav>
        <div className="flex items-center w-full gap-4 md:ml-auto md:gap-2 lg:gap-4">
          <form className="flex-1 ml-auto sm:flex-initial">
            <div className="relative">
              <SearchIcon className="absolute left-2.5 top-2.5 h-4 w-4 text-gray-500 dark:text-gray-400" />
              <Input
                className="pl-8 sm:w-[300px] md:w-[200px] lg:w-[300px]"
                placeholder="Search courses..."
                type="search"
              />
            </div>
          </form>
          <Button className="rounded-full" size="icon" variant="ghost">
            <img
              alt="Avatar"
              className="rounded-full"
              height="32"
              src="/placeholder.svg"
              style={{
                aspectRatio: "32/32",
                objectFit: "cover",
              }}
              width="32"
            />
            <span className="sr-only">Toggle user menu</span>
          </Button>
        </div>
      </header>
      <main className="flex flex-col gap-4 p-4 md:gap-8 md:p-10">
        <div className="flex items-center gap-4">
          <h1 className="text-2xl font-semibold">Welcome, Emma!</h1>
          <div className="flex items-center gap-2 ml-auto">
            <CalendarIcon className="w-4 h-4 text-gray-500 dark:text-gray-400" />
            <span className="text-sm text-gray-500 dark:text-gray-400">Fall 2023</span>
          </div>
        </div>
        <Card>
          <CardHeader className="flex items-center gap-4">
            <div className="flex items-center gap-2">
              <BookOpenIcon className="w-6 h-6" />
              <CardTitle className="text-base font-medium">Courses</CardTitle>
            </div>
            <Link className="inline-flex items-center gap-1 text-xs font-medium" href="#">
              View all
              <ChevronRightIcon className="w-4 h-4" />
            </Link>
          </CardHeader>
          <CardContent className="p-0">
            <div className="grid gap-4 text-sm">
              <Card>
                <CardContent className="flex items-center gap-4 p-4">
                  <BookOpenIcon className="w-10 h-10" />
                  <div className="grid gap-1.5">
                    <CardTitle className="text-base font-semibold">Introduction to Computer Science</CardTitle>
                    <p className="text-sm text-gray-500 dark:text-gray-400">Instructor: Dr. Smith</p>
                  </div>
                  <div className="ml-auto w-12">
                    <Button size="sm">Resume</Button>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardContent className="flex items-center gap-4 p-4">
                  <BookOpenIcon className="w-10 h-10" />
                  <div className="grid gap-1.5">
                    <CardTitle className="text-base font-semibold">History of Art</CardTitle>
                    <p className="text-sm text-gray-500 dark:text-gray-400">Instructor: Dr. Johnson</p>
                  </div>
                  <div className="ml-auto w-12">
                    <Button size="sm">Resume</Button>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardContent className="flex items-center gap-4 p-4">
                  <BookOpenIcon className="w-10 h-10" />
                  <div className="grid gap-1.5">
                    <CardTitle className="text-base font-semibold">Mathematics for Beginners</CardTitle>
                    <p className="text-sm text-gray-500 dark:text-gray-400">Instructor: Dr. Williams</p>
                  </div>
                  <div className="ml-auto w-12">
                    <Button size="sm">Resume</Button>
                  </div>
                </CardContent>
              </Card>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex items-center gap-4">
            <div className="flex items-center gap-2">
              <CalendarIcon className="w-6 h-6" />
              <CardTitle className="text-base font-medium">Upcoming</CardTitle>
            </div>
            <Link className="inline-flex items-center gap-1 text-xs font-medium" href="#">
              View all
              <ChevronRightIcon className="w-4 h-4" />
            </Link>
          </CardHeader>
          <CardContent className="p-0">
            <Table>
              <TableBody>
                <TableRow>
                  <TableCell className="w-10 font-semibold">1</TableCell>
                  <TableCell className="font-semibold">History of Art</TableCell>
                  <TableCell>Dr. Johnson</TableCell>
                  <TableCell className="text-right">2 days</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="w-10 font-semibold">2</TableCell>
                  <TableCell className="font-semibold">Mathematics for Beginners</TableCell>
                  <TableCell>Dr. Williams</TableCell>
                  <TableCell className="text-right">5 days</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="w-10 font-semibold">3</TableCell>
                  <TableCell className="font-semibold">Introduction to Computer Science</TableCell>
                  <TableCell>Dr. Smith</TableCell>
                  <TableCell className="text-right">10 days</TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex items-center gap-2">
            <AwardIcon className="w-6 h-6" />
            <CardTitle className="text-base font-medium">Grades</CardTitle>
          </CardHeader>
          <CardContent className="p-0">
            <Table>
              <TableBody>
                <TableRow>
                  <TableCell className="font-semibold">History of Art</TableCell>
                  <TableCell>Dr. Johnson</TableCell>
                  <TableCell className="text-right">A</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="font-semibold">Mathematics for Beginners</TableCell>
                  <TableCell>Dr. Williams</TableCell>
                  <TableCell className="text-right">B+</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="font-semibold">Introduction to Computer Science</TableCell>
                  <TableCell>Dr. Smith</TableCell>
                  <TableCell className="text-right">A-</TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </CardContent>
        </Card>
        <Popover>
          <PopoverTrigger asChild>
            <Button className="w-full" variant="outline">
              Open Resources
            </Button>
          </PopoverTrigger>
          <PopoverContent className="w-[300px]">
            <div>Course Materials</div>
            <div>Discussions</div>
            <div>Support</div>
          </PopoverContent>
        </Popover>
      </main>
    </div>
  )
}


function Package2Icon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 9h18v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V9Z" />
      <path d="m3 9 2.45-4.9A2 2 0 0 1 7.24 3h9.52a2 2 0 0 1 1.8 1.1L21 9" />
      <path d="M12 3v6" />
    </svg>
  )
}


function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}


function CalendarIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="18" x="3" y="4" rx="2" ry="2" />
      <line x1="16" x2="16" y1="2" y2="6" />
      <line x1="8" x2="8" y1="2" y2="6" />
      <line x1="3" x2="21" y1="10" y2="10" />
    </svg>
  )
}


function BookOpenIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2 3h6a4 4 0 0 1 4 4v14a3 3 0 0 0-3-3H2z" />
      <path d="M22 3h-6a4 4 0 0 0-4 4v14a3 3 0 0 1 3-3h7z" />
    </svg>
  )
}


function ChevronRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m9 18 6-6-6-6" />
    </svg>
  )
}


function AwardIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="8" r="6" />
      <path d="M15.477 12.89 17 22l-5-3-5 3 1.523-9.11" />
    </svg>
  )
}
